# Generated by Django 2.2 on 2019-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(),
        ),
    ]
