# Generated by Django 2.2.5 on 2019-09-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade_estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='estado_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funilaria.Estado'),
        ),
    ]
