# Generated by Django 2.2.5 on 2019-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='finalizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
