# Generated by Django 2.2.2 on 2019-09-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funilaria.OrdemDeServico'),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(null=True),
        ),
    ]
