# Generated by Django 2.2.5 on 2019-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rg',
            new_name='cpf',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='finalizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='previsao_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
