# Generated by Django 2.2 on 2019-10-08 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0003_auto_20191005_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='valor_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 17, 39, 50, 525576)),
        ),
    ]
