# Generated by Django 2.2.5 on 2019-09-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0003_auto_20190919_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemdeservico',
            old_name='finalizado',
            new_name='data_finalizacao',
        ),
    ]
