# Generated by Django 2.2 on 2019-10-08 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0004_auto_20191008_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 17, 42, 54, 720659)),
        ),
    ]
