# Generated by Django 2.2.5 on 2019-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0004_auto_20190919_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('quantidade_estoque', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='quantidade',
            new_name='quantidade_pecas',
        ),
    ]
