# Generated by Django 2.2.2 on 2019-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0004_auto_20190821_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=10)),
                ('ano', models.SmallIntegerField(default=0)),
                ('placa', models.CharField(max_length=7)),
                ('cidade', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('entrada', models.DateTimeField()),
                ('finalizado', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='customer',
            name='telefone',
            field=models.IntegerField(default=0),
        ),
    ]
