# Generated by Django 2.1.3 on 2019-09-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0005_auto_20190920_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='quantidade_pecas',
            new_name='quantidade',
        ),
    ]
