# Generated by Django 2.2 on 2019-10-08 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0005_auto_20191008_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='total_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 17, 44, 36, 226892)),
        ),
    ]
