# Generated by Django 2.2.2 on 2019-08-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0005_auto_20190822_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(),
        ),
    ]
