# Generated by Django 2.1.3 on 2019-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0006_auto_20190920_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='quantidade_pecas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
