# Generated by Django 2.2 on 2019-10-08 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0006_auto_20191008_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 18, 2, 19, 171479)),
        ),
    ]
