# Generated by Django 2.2.5 on 2019-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0006_auto_20190930_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='placa_veiculo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
