# Generated by Django 2.2.2 on 2019-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0006_auto_20190822_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funilaria.Veiculo'),
        ),
    ]
