# Generated by Django 2.2 on 2019-10-09 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0007_auto_20191008_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 9, 4, 14, 835000)),
        ),
    ]
