# Generated by Django 2.2.2 on 2019-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0009_auto_20190823_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='customer',
            name='ano_veiculo',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='cidade_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cor_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='estado_veiculo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marca_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modelo_veiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bairro',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endereco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
