# Generated by Django 2.2 on 2019-10-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0009_auto_20191010_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 16, 59, 30, 71493)),
        ),
    ]
