# Generated by Django 2.2 on 2019-10-10 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0010_auto_20191010_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='selecionado',
            new_name='finalizado',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 17, 1, 20, 536258)),
        ),
    ]
