# Generated by Django 2.2 on 2019-10-10 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0011_auto_20191010_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 17, 3, 32, 101557)),
        ),
    ]
