# Generated by Django 2.2.2 on 2019-08-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0011_auto_20190823_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='entrada_veiculo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='saida_veiculo',
        ),
    ]
