# Generated by Django 2.2.2 on 2019-08-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0012_auto_20190824_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ano_veiculo',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bairro',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cidade_veiculo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cor_veiculo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endereco',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='estado_veiculo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marca_veiculo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modelo_veiculo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='placa_veiculo',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
