# Generated by Django 2.2.2 on 2019-08-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0013_auto_20190824_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bairro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
    ]
