# Generated by Django 2.2 on 2019-10-10 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0014_auto_20191010_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='ordem_servico',
            new_name='ordem_de_servico',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 17, 55, 51, 688868)),
        ),
    ]
