# Generated by Django 2.2.2 on 2019-09-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0014_auto_20190824_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funilaria.Customer')),
                ('reparos_necessarios', models.TextField(max_length=200)),
                ('entrada', models.DateField()),
                ('prazo_entrega', models.DateField()),
                ('finalizado', models.DateField()),
            ],
            bases=('funilaria.customer',),
        ),
    ]
