# Generated by Django 2.2 on 2019-10-10 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0015_auto_20191010_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='carrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funilaria.Carrinho'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 10, 18, 10, 5, 94230)),
        ),
    ]
