# Generated by Django 2.2 on 2019-10-12 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0016_auto_20191010_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=datetime.datetime(2019, 10, 12, 12, 47, 23, 222452)),
        ),
    ]
