# Generated by Django 2.2 on 2019-10-13 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0019_auto_20191012_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funilaria.Carrinho'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='prazo_entrega',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
