# Generated by Django 2.2.2 on 2019-08-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='funilaria.Customer')),
                ('cpf', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
            bases=('funilaria.customer',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='funilaria.Customer')),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
            ],
            bases=('funilaria.customer',),
        ),
    ]
