# Generated by Django 2.2.2 on 2019-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=4)),
                ('placa', models.CharField(max_length=7)),
                ('cidade', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cep',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='customer',
            name='telefone',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
