# Generated by Django 2.2.2 on 2019-08-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funilaria', '0003_auto_20190820_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=10)),
                ('ano', models.SmallIntegerField(max_length=4)),
                ('placa', models.CharField(max_length=7)),
                ('cidade', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telefone',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
